### ISSUE TITLE
sails.getBaseURL() is deprecated.

### ISSUE THREAD

**Issue by tom-sherman** [trailsjs/sails-auth#140]
As `getBaseURL()` is being deprecated in Sails v1.0, there should be implemented a more elegant way to define this.

[The offending bit in `passport.js`](https://github.com/langateam/sails-auth/blob/master/api/services/passport.js#L292):

``` javascript
var baseUrl = sails.getBaseurl();

switch (protocol) {
  case 'oauth':
  case 'oauth2':
    options.callbackURL = url.resolve(baseUrl, callback);
    break;

  case 'openid':
    options.returnURL = url.resolve(baseUrl, callback);
    options.realm     = baseUrl;
    options.profile   = true;
    break;
}
```

---

[Reference](http://sailsjs.org/documentation/reference/application/sails-get-base-url):

> There is no reliable, cross-platform way to automatically detect the external URL of a running Sails app (or any other Node app). In mission-critical situations, you are advised to pre-determine the URL and save it in a custom environment-dependent configuration value (e.g. sails.config.appUrl) that you can reference elsewhere in the app.

**Comment by tjwebb** [comment]
> There is no reliable, cross-platform way to automatically detect the external URL of a running Sails app

So, what should we do?

**Comment by tom-sherman** [comment]
Could look for a few configuration values before using this deprecated method. Maybe then add an error message to advise to set one up?

**Comment by scott-wyatt** [comment]
I agree, I think that this should be set through an environment variable in future releases.

**Comment by Garland220** [comment]
This will fail if 'sails.config.appUrl' is undefined. 

I would suggest adding a check for undefined as well:
`
      var baseUrl = '';
      if (sails.config.appUrl && sails.config.appUrl !== null) {
        baseUrl = sails.config.appUrl;
      }
      else {
        sails.log.warn('Please add "appUrl" configuration value.');
        baseUrl = sails.getBaseurl();
      }
`

**Comment by tom-sherman** [comment]
@Garland220 That's strange, I specifically remember testing for this case and it produced the expected result (a warning).

**Comment by TheSinding** [comment]
Is there a fix for this issue?

**Comment by tom-sherman** [comment]
@TheSinding Which issue are you referring to? Both my solution and the hotfix have been merged into master

**Comment by 0aps** [comment]
@tom-sherman he probably says that because your solution is not yet publish into npm.

**Comment by TheSinding** [comment]
Sorry I didnt answer until now @tom-sherman.
Yeah @0aps is properly correct, when I tried with Sail 1.0 and the auth lib, I kept getting an sails.baseUrl() error..

**Comment by abalad** [comment]
Same here

**Comment by amoritan** [comment]
(+1) It would be great if the npm package was updated with the latest release available on GitHub.

**Comment by lauragift21** [comment]
Is there a fix for this error?

**Comment by michaelfahmy** [comment]
Any fix?!!! It's too long since this issue has been opened.
Please update the package!

**Comment by tjwebb** [comment]
see:
- https://github.com/trailsjs/sails-auth/issues/126
- https://github.com/trailsjs/sails-auth/issues/118
