### ISSUE TITLE
Local login doesn't work.

### ISSUE THREAD

**Issue by mak4alex** [trailsjs/sails-auth#65]
Hello! I try to login and post user's email and pass to /auth/local/ but it get 403 response. Method exports.login from sails-auth/api/services/protocols/local.js (123) doesn't called. Then i made some fix in sails-auth/api/services/passport.js (256): 

``` javascript
this.authenticate(provider, next)(req, res, req.next);
```

to

``` javascript
this.protocols.local.login(req, req.body.email, req.body.password, next);
```

It works alright, but looks bad. Can somebody help me use sails-auth in the right way?

**Comment by bitsonic** [comment]
The regular this.authenticate does, work - however further documentation of the passport-local usage is Absolutely necessary in my opinion.

- Creating a user is probably done in most cases using either a username, email. Most developers probably expect values from local user models such as username, to transfer over to the required parameters necessary for login. 

- This is not the case however; Local login at /local/auth needs the following parameters:

```
identifier:         somethinguser
password:       somethingpassword
```

Note the use of **identifier** - username is not a valid parameter for local authentication.
This might not be a bug perse, but it is a documentation issue. I do understand that writing documentation can be a cumbersome task, however it would make sails-auth infinitely better and probably more popular. 

Whilst documentation of sails-auth has improved somewhat over the last month, further docs contributions (e.g. extended instructions + examples) could make sails-auth as a whole much better.
